initItems()
{
itemIDs := []
items.push("Führerschein") ;1
items.push("Helischein")
items.push("Motorradschein")
items.push("Bootsschein")
items.push("Angelschein")
items.push("Waffenschein")
items.push("Zerissene Jacke `(Müll`)")
items.push("Zerissene Lederjacke `(Müll`)")
items.push("Zackenbarsch `(Fisch`)")
items.push("Roter Schnapper `(Fisch`)")
items.push("Zerissene Hose `(Müll`)")
items.push("Forelle `(Fisch`)")
items.push("Blauer Marlin `(Fisch`)")
items.push("Rostige Dose `(Müll`)")
items.push("Makrele `(Fisch`)")
items.push("Wolfsbarsch `(Fisch`)")
items.push("Faule Schuhe `(Müll`)")
items.push("Hecht `(Fisch`)")
items.push("Fächerfisch `(Fisch`)")
items.push("Rostiges Metall `(Müll`)")
items.push("Thunfisch `(Fisch`)")
items.push("Aal `(Fisch`)")
items.push("Delfin `(Fisch`)")
items.push("Hai `(Fisch`)")
items.push("Schildkröte `(Fisch`)")
items.push("Katzenfisch `(Fisch`)")
items.push("Dollarscheine `(Geldbeutel`)")
items.push("Schwertfisch `(Fisch`)")
items.push("Reh `(Fleisch`)")
items.push("Benzin `(Kanister`)")
items.push("Diesel `(Kanister`)")
items.push("Kerosin `(Kanister`)")
items.push("10 Dollar `(Handykarte`)")
items.push("20 Dollar `(Handykarte`)")
items.push("100 Dollar `(Handykarte`)")
items.push("Sprengstoff")
items.push("Kunststoff")
items.push("Bomben `(Normal`)")
items.push("Bomben `(RC`)")
items.push("Hanfsamen")
items.push("Hanfpflanze")
items.push("Joint")
items.push("Mohnsamen")
items.push("Mohn")
items.push("Heroin Flasche")
items.push("Speed Materialien")
items.push("Speed")
items.push("Tabak")
items.push("Zigaretten")
items.push("Zigarren")
items.push("Schlagring `(Waffe`)")
items.push("Golfschläger `(Waffe`)")
items.push("Schlagstock `(Waffe`)")
items.push("Messer `(Waffe`)")
items.push("Baseballschläger `(Waffe`)")
items.push("Schaufel `(Waffe`)")
items.push("Pool Queue `(Waffe`)")
items.push("Katana `(Waffe`)")
items.push("Kettensäge `(Waffe`)")
items.push("Violetter Dildo `(Waffe`)")
items.push("Dildo `(Waffe`)")
items.push("Vibrator `(Waffe`)")
items.push("Silber Vibrator `(Waffe`)")
items.push("Blumen `(Waffe`)")
items.push("Gehstock `(Waffe`)")
items.push("Granate `(Munition`)")
items.push("Tränengas `(Munition`)")
items.push("Molotov Cocktail `(Munition`)")
items.push("Pistole `(Munition`)")
items.push("Tazer `(Waffe`)")
items.push("Desert Eagle `(Munition`)")
items.push("Shotgun `(Munition`)")
items.push("Sawnoff Shotgun `(Munition`)")
items.push("Combat Shotgun `(Munition`)")
items.push("Micro SMG/Uzi `(Munition`)")
items.push("MP5 `(Munition`)")
items.push("AK-47 `(Munition`)")
items.push("M4 `(Munition`)")
items.push("Tec-9 `(Munition`)")
items.push("Country Rifle `(Munition`)")
items.push("Sniper Rifle `(Munition`)")
items.push("RPG `(Munition`)")
items.push("HS Rocket `(Munition`)")
items.push("Flamenwerfer `(Munition`)")
items.push("Minigun `(Munition`)")
items.push("Special Sniper `(Munition`)")
items.push("Albit `(Stein`)")
items.push("Bergkristall `(Stein`)")
items.push("Beryllonit `(Stein`)")
items.push("Diamant `(Stein`)")
items.push("Goshenit `(Stein`)")
items.push("Hambergit `(Stein`)")
items.push("Leucit `(Stein`)")
items.push("Petalit `(Stein`)")
items.push("Phenakit `(Stein`)")
items.push("Hackmannit `(Stein`)")
items.push("Morganit `(Stein`)")
items.push("Piemontit `(Stein`)")
items.push("Rhodochrosit `(Stein`)")
items.push("Rhodonit `(Stein`)")
items.push("Rosaquarz `(Stein`)")
items.push("Roter Beryll `(Stein`)")
items.push("Thulit `(Stein`)")
items.push("Tugtupit `(Stein`)")
items.push("Bernstein `(Stein`)")
items.push("Citrin `(Stein`)")
items.push("Feueropal `(Stein`)")
items.push("Goldberyll `(Stein`)")
items.push("Pyrit `(Stein`)")
items.push("Amazonit `(Stein`)")
items.push("Aventurin-Quarz `(Stein`)")
items.push("Brasilianit `(Stein`)")
items.push("Chrysokoll `(Stein`)")
items.push("Chrysopras `(Stein`)")
items.push("Dioptas `(Stein`)")
items.push("Jade `(Stein`)")
items.push("Malachit `(Stein`)")
items.push("Smaragd `(Stein`)")
items.push("Azurid `(Stein`)")
items.push("Aquamarin `(Stein`)")
items.push("Amethyst `(Stein`)")
items.push("Lapislazuli `(Stein`)")
items.push("Sodalith `(Stein`)")
items.push("Tansanit `(Stein`)")
items.push("Telefonbuch")
items.push("Lotto Ticket")
items.push("Hilfsbogen")
items.push("Repair Kit")
items.push("Dünger")
items.push("Wasser")
items.push("2 Liter Flasche")
items.push("Kohle")
items.push("Eisen `(Erz`)")
items.push("Bauxit `(Erz`)")
items.push("Eisen `(Metall`)")
items.push("Aluminium `(Metall`)")
items.push("öl")
items.push("Apfel")
items.push("Kartoffel")
items.push("Milch")
items.push("Weizen")
items.push("Frostschutzmittel")
items.push("Erkältungstabletten")
items.push("Methamphetamin")
items.push("Brechstange")
items.push("Würfel")
items.push("Flugschein `(Leichtflugzeuge`)")
items.push("Flugschein `(Großflugzeuge`)")
items.push("Fallschirm")
items.push("Kamera")
items.push("Ersatzrad")
items.push("Drogenschnelltest") ;152
Return itemIDs
}