:?:/help keybinder::
Suspend Permit 
AddChatMessage("{45B6FE}Keybinder: {FFFFFF}Hotekeys: AFK-Timer: F2 --> An | F3 --> Aus")
AddChatMessage("{45B6FE}Keybinder: {FFFFFF}Hilfe für bestimmte Keybinder Funktionen:")
AddChatMessage("{45B6FE}Keybinder: {FFFFFF}Freundesliste: /help FL | Events: /help event")
return

:?:/help fl::
Suspend Permit 
Sleep 300
ShowDialog(0, "Freundesliste Befehle", "{00FF00}*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*`n`n{666666}/fl{00FFFF} ={ffffff} Freundesliste anzeigen`n{666666}/fladd{00FFFF} ={ffffff} Freund hinzufügen`n{666666}/fldel{00FFFF} ={ffffff} Freund entfernen`n{666666}/flreset{00FFFF} ={ffffff} Freundesliste leeren`n Die Freundesliste wurde von {006600} Ryan {FFFFFF} erstellt und von {FFFF80} Darkari  {FFFFFF} editiert.`n`n{660028}*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*", "Schließen","", 65)
return

:?:/nrhelp::
Suspend Permit
Sleep, 200
;ShowDialog(0, "News Reporter Befehle" , "{45B6FE}*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*`nWerbung `n {FFFFFF}/nrwerbung --> News Reporter Fraktionswerbung `n /servicead --> Werbund für Dienstleistungen der News Reporter `n {45B6FE}Grußrunde `n {FFFFFF}/gstart --> Grußrunde starten `n /gstop --> Grußrunde beenden `n {45B6FE}Buchstabensalat   `n {FFFFFF}/bststart  --> Startet das Event `n /bstnext --> Eine Runde spielen, bis die festgelgte Anzahl an Runden gepielt wurde. `n /bstedit --> Event nach start bearbeiten, z.B. bei Erhöhung des Gewinns `n {45B6FE}Fang den Sultan   `n {FFFFFF}/fstart --> Startet das Event `n /fstop --> Beendet das Event `n /fsedit --> Event nach start bearbeiten, z.B. bei Erhöhung des Gewinns `n {45B6FE}Finde den News Van   `n {FFFFFF}/fnvstart --> Startet das Event  `n /fnvstop --> Beendet das Event `n /fnvedit --> Event nach start bearbeiten, z.B. bei Erhöhung des Gewinns `n {45B6FE}Pinker Roller   `n {FFFFFF}/prstart --> Startet das Event  `n /prstop --> Beendet das Event `n /predit --> Event nach start bearbeiten, z.B. bei Erhöhung des Gewinns `n {45B6FE}Quiz   `n {FFFFFF}/qstart --> Startet das Event `n /qnext  --> Eine Runde spielen, bis die festgelgte Anzahl an Runden gepielt wurde. `n /qedit --> Event nach start bearbeiten, z.B. bei Erhöhung des Gewinns `n {45B6FE}Tuningevent   `n {FFFFFF}/tstart --> Startet das Event `n /tstop --> Beendet das Event `n /tedit --> Event nach start bearbeiten, z.B. bei Erhöhung des Gewinns `n {45B6FE}*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*", "Schließen", "", 65)
ShowDialog(0 , "Event Befehle", "{45B6FE}Werbung `n {FFFFFF}/nrwerbung --> News Reporter Fraktionswerbung `n /servicead --> Werbung für Dienstleistungen der News Reporter `n `n {45B6FE}Grußrunde `n {FFFFFF}/gstart --> Grußrunde starten `n /gstop --> Grußrunde beenden `n`n  {45B6FE}Buchstabensalat   `n {FFFFFF}/bststart  --> Startet das Event `n /bstnext --> Eine Runde spielen, bis die festgelgte Anzahl an Runden gepielt wurde. `n /bstedit --> Event nach start bearbeiten, z.B. bei Erhöhung des Gewinns `n`n  {45B6FE}Fang den Sultan   `n {FFFFFF}/fstart --> Startet das Event `n /fstop --> Beendet das Event `n /fsedit --> Event nach start bearbeiten, z.B. bei Erhöhung des Gewinns `n`n  {45B6FE}Finde den News Van   `n {FFFFFF}/fnvstart --> Startet das Event  `n /fnvstop --> Beendet das Event `n /fnvedit --> Event nach start bearbeiten, z.B. bei Erhöhung des Gewinns `n`n  {45B6FE}Pinker Roller   `n {FFFFFF}/prstart --> Startet das Event  `n /prstop --> Beendet das Event `n /predit --> Event nach start bearbeiten, z.B. bei Erhöhung des Gewinns `n `n {45B6FE}Quiz   `n {FFFFFF}/qstart --> Startet das Event `n /qnext  --> Eine Runde spielen, bis die festgelgte Anzahl an Runden gepielt wurde. `n /qedit --> Event nach start bearbeiten, z.B. bei Erhöhung des Gewinns `n`n  {45B6FE}Tuningevent   `n {FFFFFF}/tstart --> Startet das Event `n /tstop --> Beendet das Event `n /tedit --> Event nach start bearbeiten, z.B. bei Erhöhung des Gewinns `n`n  {45B6FE}*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+**+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*", "Schließen", "", 28)
return

:?:/help event::
Suspend Permit
Sleep, 200
;ShowDialog(4, "News Reporter Befehle", "{45B6FE}News`t`n{FFFFFF}/nws`tNews aus der Settings.ini austrahlen`n`t`n{45B6FE}Werbung`t`n{FFFFFF}/nrwerbung`tNews Reporter - Fraktionswerbung`n/servicead`tWerbung für Dienstleistungen der News Reporter`n`t`n{45B6FE}Grußrunde`t`n{FFFFFF}/gstart`tGrußrunde starten`n/gstop`tGrußrunde beenden`n`t`n{45B6FE}Buchstabensalat`t`n{FFFFFF}/bststart`tStartet das Event`n/bstnext`tEine Runde spielen, bis die festgelgte Anzahl an Runden gespielt wurde.`n/bstedit`tEvent nach dem Start bearbeiten, z.B. bei Erhöhung des Gewinns`n`t`n{45B6FE}Fang den News Sultan`t`n{FFFFFF}/fstart`tStartet das Event`n/fstop`tBeendet das Event`n/fsedit`tEvent nach dem Start bearbeiten, z.B. bei Erhöhung des Gewinns`n`t`n{45B6FE}Finde den News Van`t`n{FFFFFF}/fnvstart`tStartet das Event`n/fnvstop`tBeendet das Event`n/fnvedit`tEvent nach dem Start bearbeiten, z.B. bei Erhöhung des Gewinns`n`t`n{45B6FE}Pinker Roller`n{FFFFFF}/prstart`tStartet das Event`n/prstop`tBeendet das Event`n/predit`tEvent nach dem Start bearbeiten, z.B. bei Erhöhung des Gewinns`n`t`n{45B6FE}Quiz`t`n{FFFFFF}/qstart`tStartet das Event`n/qnext`tEine Runde spielen, bis die festgelgte Anzahl an Runden gespielt wurde.`n/qedit`tEvent nach dem Start bearbeiten, z.B. bei Erhöhung des Gewinns`n`t`n{45B6FE}Tuningevent`t`n{FFFFFF}/tstart`tStartet das Event`n/tstop`tBeendet das Event`n/tedit`tEvent nach dem Start bearbeiten, z.B. bei Erhöhung des Gewinns", "Schließen", "", 35)
;Text := "{45B6FE}News`t`n{FFFFFF}/nws`tNews aus der Settings.ini austrahlen`n`t`n{45B6FE}Werbung`t`n{FFFFFF}/nrwerbung`tNews Reporter - Fraktionswerbung`n/servicead`tWerbung für Dienstleistungen der News Reporter`n`t`n{45B6FE}Grußrunde`t`n{FFFFFF}/gstart`tGrußrunde starten`n/gstop`tGrußrunde beenden`n`t`n{45B6FE}Buchstabensalat`t`n{FFFFFF}/bststart`tStartet das Event`n/bstnext`tEine Runde spielen, bis die festgelgte Anzahl an Runden gespielt wurde.`n/bstedit`tEvent nach dem Start bearbeiten, z.B. bei Erhöhung des Gewinns`n`t`n{45B6FE}Fang den News Sultan`t`n{FFFFFF}/fstart`tStartet das Event`n/fstop`tBeendet das Event`n/fsedit`tEvent nach dem Start bearbeiten, z.B. bei Erhöhung des Gewinns`n`t`n{45B6FE}Finde den News Van`t`n{FFFFFF}/fnvstart`tStartet das Event`n/fnvstop`tBeendet das Event`n/fnvedit`tEvent nach dem Start bearbeiten, z.B. bei Erhöhung des Gewinns`n`t`n{45B6FE}Pinker Roller`n{FFFFFF}/prstart`tStartet das Event`n/prstop`tBeendet das Event`n/predit`tEvent nach dem Start bearbeiten, z.B. bei Erhöhung des Gewinns`n`t`n{45B6FE}Quiz`t`n{FFFFFF}/qstart`tStartet das Event`n/qnext`tEine Runde spielen, bis die festgelgte Anzahl an Runden gespielt wurde.`n/qedit`tEvent nach dem Start bearbeiten, z.B. bei Erhöhung des Gewinns`n`t`n{45B6FE}Tuningevent`t`n{FFFFFF}/tstart`tStartet das Event`n/tstop`tBeendet das Event`n/tedit`tEvent nach dem Start bearbeiten, z.B. bei Erhöhung des Gewinns"
ShowDialog(4, "Event Befehle", "{45B6FE}News`t`n{FFFFFF}/nws`tNews aus der Settings.ini austrahlen`n`t", "Schließen", "", 78)
return

:?:/help::
:?:/hilfe::
Suspend Permit 
SendChat("/help")
Sleep 500
AddChatMessage("{45B6FE}Info: {FFFFFF}Die Hilfe für den Keybinder findest du unter /help keybinder")
Return